version: "3.8"

services:
  fastsam_backend:
    container_name: fastsam-backend
    build:
      context: .
      args:
        TEST_ENV: ${TEST_ENV:-production}
    image: fastsam-backend:latest
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    env_file:
      - .env
    environment:
      - USE_ORG_MIDDLEWARE=true
      - LOG_LEVEL=INFO
    ports:
      - "9090:9090"
    volumes:
      - "./data/server:/data"
      - "./.env:/app/.env:ro"
    networks:
      - label-studio-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  label-studio-network:
    external: true