services:
  sam2-backend:
    container_name: sam2-backend
    image: gavinlouuu/sam2-backend:v0
    build:
      context: .
      args:
        TEST_ENV: ${TEST_ENV}

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]


    env_file:
      - .env
    ports:
      - "9093:9090"
    volumes:
      - "./data/server:/data"
    networks:
      - label-studio-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  label-studio-network:
    external: true